### ISSUE TITLE
真机无法热更

### ISSUE THREAD

**Issue by h4acda** [johnno1962/HotReloading#101]
Broadcasting to en2.10:169.254.255.255 to locate InjectionIII host...
Broadcasting to en0.14:192.168.1.255 to locate InjectionIII host...
💉 Connecting to 192.168.1.245 (169.254.129.194)...
💉 InjectionIII connected /Volumes/公司固态/Documents/h4test/h4test.xcworkspace
💉 Watching files under the directory /Volumes/公司固态/Documents/h4test
💉 💉 ⚠️ Your project file seems to be in the Desktop or Documents folder and may prevent InjectionIII working as it has special permissions.
💉 Compiling /Volumes/公司固态/Documents/h4test/h4test/Controllers/ViewController.swift
💉 Loading .dylib ...
💉 ⚠️ dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval101.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval101.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval101.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval101.dylib), but incompatible platform (have (iOS-sim), need (iOS)))
💉 ⚠️ Clean build folder when switching platform
💉 ⚠️ Injection error: Error Domain=SwiftEval Code=-1 "dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval101.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval101.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval101.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval101.dylib), but incompatible platform (have (iOS-sim), need (iOS)))
💉 ⚠️ Clean build folder when switching platform" UserInfo={NSLocalizedDescription=dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval101.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval101.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval101.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval101.dylib), but incompatible platform (have (iOS-sim), need (iOS)))
💉 ⚠️ Clean build folder when switching platform}
💉 Compiling /Volumes/公司固态/Documents/h4test/h4test/Controllers/ViewController.swift
💉 Loading .dylib ...
💉 ⚠️ dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval102.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval102.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval102.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval102.dylib), but incompatible platform (have (iOS-sim), need (iOS)))
💉 ⚠️ Clean build folder when switching platform
💉 ⚠️ Injection error: Error Domain=SwiftEval Code=-1 "dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval102.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval102.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval102.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval102.dylib), but incompatible platform (have (iOS-sim), need (iOS)))
💉 ⚠️ Clean build folder when switching platform" UserInfo={NSLocalizedDescription=dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval102.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval102.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval102.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/304DE21E-9FE6-40A9-BAD5-4F5E798631F1/tmp/eval102.dylib), but incompatible platform (have (iOS-sim), need (iOS)))
💉 ⚠️ Clean build folder when switching platform}

**Comment by johnno1962** [comment]
Hi, this happens when you switch from build for a simulator to building  for a real device. Close your project to clear the logs then re-open it and build it for the device and it should choose the correct logs and `rm /tmp/*_builds.plist` to clear the cache.

**Comment by h4acda** [comment]
Clean Build Folder 然后第一次真机运行时  Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
poll: hangup
第二次将没有错误

**Comment by h4acda** [comment]
刷新功能好使了
