### ISSUE TITLE
What to do if I don't see any message in the console?

### ISSUE THREAD

**Issue by zomars** [johnno1962/HotReloading#21]
> You should see a message that the app has connected and which directories it is watching for source file changes. 

I'm pretty sure I've followed the steps correctly. I might be wrong tho. The main difference I found from my project and the demo project is that I don't use SwiftUI.

Any help is greatly appreciated 🙏🏽

**Comment by johnno1962** [comment]
This is in the simulator right?

**Comment by zomars** [comment]
Yes. I'm using the simulator. Do I have to call the injected method on each view?

**Comment by johnno1962** [comment]
You really should see some message if you added the SPM package correctly. Did you select the HotReloading target to add?

**Comment by zomars** [comment]
Yup. I'll try to enumerate the steps that I've followed.

**Comment by johnno1962** [comment]
I'm closing this now. If you can't get HotReloading the Swift Package to work you're just as well off using the [InjectionIII app](https://github.com/johnno1962/InjectionIII/releases/tag/2.8.6) if you add a line to load a bundle instead.
