### ISSUE TITLE
How can I build only in debug environment

### ISSUE THREAD

**Issue by GG526** [johnno1962/HotReloading#24]

**Comment by johnno1962** [comment]
Hi, unfortunately this is not available using the Swift Packager.

**Comment by GG526** [comment]
thanks.

**Comment by johnno1962** [comment]
I'm closing this now. An alternative to the Swift package is using the [InjectionIII app](https://github.com/johnno1962/InjectionIII) which is the same code where you add a line to load a bundle instead inside an #if DEBUG
