### ISSUE TITLE
There is an error in using xcode 13 according to the operation in the video

### ISSUE THREAD

**Issue by zuqiu123** [johnno1962/HotReloading#30]
video link: https://twitter.com/sir_kif/status/1368644206789615617
xcode: Version 13.0 (13A233)

Multiple commands produce '/Users/admin/Library/Developer/Xcode/DerivedData/HotSwiftUI-bphptxjidulartdyzngcqjbfxuid/Build/Intermediates.noindex/HotSwiftUI.build/Debug-iphonesimulator/HotSwiftUI.build/Objects-normal/arm64/HotSwiftUI.swiftmodule':

1) Target 'HotSwiftUI' (project 'HotSwiftUI') has compile command for Swift source files
2) Target 'HotSwiftUI' (project 'HotSwiftUI') has compile command for Swift source files
![image](https://user-images.githubusercontent.com/15611129/134069992-b2741db1-0ba0-4782-8f26-921e59166ce3.png)

build fail

**Comment by johnno1962** [comment]
Hi, It's difficult to say what the problem is here without knowing more about your project. I have used "HotSwiftUI" with Xcode 13 without seeing this problem. Have you used it before with Xcode 12?

**Comment by zuqiu123** [comment]
No, I use the xcode13 beat version. I cleared the cache and reset it.
I feel that this will refresh automatically. I must set 
```swift
#if debug for the view to be modified in advance
@ObservedObject var iO = injectionObserver
#
```
Then set debug view
```swift
. erasetoanyview ()
```
 to debug it dynamically. If a view is not set, it will still be a little troublesome to run it again

**Comment by johnno1962** [comment]
All I can suggest is trying, getting it working in Xcode 12 before trying Xcode 13 again.

**Comment by zuqiu123** [comment]
Thank you idol, I will close this video
