### ISSUE TITLE
AppCode Support

### ISSUE THREAD

**Issue by saim80** [johnno1962/HotReloading#34]
I'm aware of the fact that AppCode's InjectionIII plugin is available separately. But, I wish I can use HotReloading project directly due to the fact that it is super easy to integrate with Swift Package Manager.

After importing HotReloading via SPM, the app launches but hot reloading doesn't seem to work. I'm guessing the intermediate path used by AppCode is different. (just guessing...) Anyway, I wish HotReloading works with AppCode too.

Thanks for this awesome project.

**Comment by johnno1962** [comment]
When you say "doesn't seem to work" what happens/doesn't happen. Does the menu bar app run? Does it connect (icon goes orange)? Is there an error message you could tell me?

**Comment by saim80** [comment]
@johnno1962 Sorry about the confusion. It was simply that my code change didn't get updated right away when I tried with AppCode. But, I realized that I didn't set up the injected function nor notification. It is working now.

**Comment by saim80** [comment]
@johnno1962 Ha.. I'm getting confused with the whole thing. I thought HotReloading was working but it was a separate issue that caused a confusion for me. I see this error message when I save the Swift file from AppCode:

🔥 Loading .dylib ...
**objc[18470]: Class _TtC12MightybellUI23SpaceChatViewController is implemented in both /Users/saim/Library/Caches/JetBrains/AppCode2021.2/DerivedData/MightybellApp-ailkgvaqfypilmgiumlvwalytxms/Build/Products/Debug-iphonesimulator/MightybellUI.framework/MightybellUI (0x107505918) and /Users/saim/Library/Developer/CoreSimulator/Devices/017B587A-8521-429E-9203-E48076FA33D4/data/Containers/Data/Application/4CCB7923-E926-42FB-9412-26F84FA1AF19/tmp/eval117.dylib (0x123b3a628). One of the two will be used. Which one is undefined.**
🔥 Loaded .dylib - Ignore any duplicate class warning ⬆️
🔥 Injected class 'MightybellUI.SpaceChatViewController' (8,6)

**Comment by saim80** [comment]
Oh.. Before this, I also had to not only link but also embed HotReloading library to make a crash go away. That crash didn't happen for Xcode.

**Comment by saim80** [comment]
Here's the message from the crash

dyld: Library not loaded: @rpath/HotReloading.framework/HotReloading
  Referenced from: /Users/saim/Library/Developer/CoreSimulator/Devices/017B587A-8521-429E-9203-E48076FA33D4/data/Containers/Bundle/Application/698190B8-4336-4109-AA04-F1DE6DEB2A7B/MN Staging  Navigation.app/MN Staging  Navigation
  Reason: image not found

**Comment by saim80** [comment]
My issue was linker flag misconfiguration. Sorry about the noise!

**Comment by johnno1962** [comment]
👍

**Comment by ton1n8o** [comment]
@johnno1962 First of all thanks for such a great job supporting this project!

Not sure if I'm doing something wrong or what but, I do have my project using `HotReloading` and it works great on Xcode 14.1 however when I open the same project using `AppCode` ( and specify the same Xcode version within Tools > Xcode ) as soon as I update any file I get a `Re-compilation failed` message.

Am I missing something?

**Comment by johnno1962** [comment]
Hi, I don't know. Can you tell me a little bit more detail of the exact message you're seeing? Have you checked the command.sh script file it mentions to see if it is valid? HotReloading as a package is slowly being phased out in favour of just loading the iOSInjection.bundle from the app but not running the app a.k.a. "Standalone Injection" (if you're allowed to use the [binary releases](https://github.com/johnno1962/InjectionIII/releases)). Perhaps you could try that?

**Comment by ton1n8o** [comment]
> Hi, I don't know. ...

Hi there, thanks for replying!

As I've seen it has something to do with the iOS versions I'm running, I've doubled check and, both `Xcode` & `AppCode` do trigger the same error when running my app on `iOS 14.2`, when running it on `iOS 16`+, it just works.

`ld: warning: -undefined dynamic_lookup is deprecated on iOS Simulator
ld: warning: object file (/Users/user_folder/Library/Developer/CoreSimulator/Devices/BE1565CF-F8F7-4864-BBD0-51A765EEBF27/data/Containers/Data/Application/350B32DE-146C-40C0-94E7-7210754EEDFE/tmp/eval101.o) was built for newer iOS Simulator version (13.0) than being linked (9.0)`

**Comment by johnno1962** [comment]
Ah, I see. You can ignore the ld warning until they actually deprecate it but in fact, since Xcode 14 I've not seen an instance where you need to use `-undefined dynamic_lookup` which was a workaround for another problem so you can remove that from your "Other Linker Flags" now.

**Comment by ton1n8o** [comment]
Well, I'm not sure I can tweak this flag, I didn't set it up.

**Comment by johnno1962** [comment]
It's a warning.
