### ISSUE TITLE
Undefined symbol _FSEventStream* in FileWatcher

### ISSUE THREAD

**Issue by tete1030** [johnno1962/HotReloading#42]
I imported the HotReloading target in my project and it complains about these symbols' missing  for both simulator and real device.

```
Undefined symbols for architecture x86_64:
  "_FSEventStreamScheduleWithRunLoop", referenced from:
      HotReloading.FileWatcher.init(root: Swift.String, callback: (__C.NSArray, Swift.String) -> ()) -> HotReloading.FileWatcher in HotReloading.o
  "_FSEventStreamCreate", referenced from:
      HotReloading.FileWatcher.init(root: Swift.String, callback: (__C.NSArray, Swift.String) -> ()) -> HotReloading.FileWatcher in HotReloading.o
  "_FSEventStreamStart", referenced from:
      HotReloading.FileWatcher.init(root: Swift.String, callback: (__C.NSArray, Swift.String) -> ()) -> HotReloading.FileWatcher in HotReloading.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tete1030** [comment]
My project has some objc code, so I added the following to other linker flags. It worked

```
-Xlinker -undefined -Xlinker dynamic_lookup
```

if this is not an issue, please close this.

**Comment by johnno1962** [comment]
Hi, Good fix! What version of Xcode was this?

**Comment by tete1030** [comment]
xcode 13.3 (13E113)

**Comment by johnno1962** [comment]
And it's working OK. Strange you got the error and were able to fix it. This "standalone" injection is quite new.

**Comment by tete1030** [comment]
I found the fix from your advice [here](https://github.com/johnno1962/InjectionIII#limitationsfaq). Not sure if the same cause

**Comment by johnno1962** [comment]
`-Xlinker -undefined -Xlinker dynamic_lookup` is always a good fallback even if it gives you a warning. Thanks for reporting this, closing now.

**Comment by johnno1962** [comment]
I've updated the project README with your fix. Thanks!

**Comment by tete1030** [comment]
Thank you for your help and this great tool
