### ISSUE TITLE
Breakpoint not work after injection

### ISSUE THREAD

**Issue by TMTBO** [johnno1962/HotReloading#43]
After I changed my code, the breakpoint will not work correctly.

This is the [Example.zip](https://github.com/johnno1962/HotReloading/files/8439261/Example.zip)

MacOS: 12.3
XCode: 13.3
iPhone: iPhone 7 Plus 14.7.1
 
```
🔥 HotReloading connected /Users/xxx/Project/Example/Example.xcodeproj
🔥 Watching files under /Users/xxx/Project/Example
🔥 Watching files under /Users/xxx/Project/HotReloading
🔥 Compiling /Users/xxx/Project/Example/Example/ViewController.m
🔥 InjectionLoader: ⚠️ This implementation is available to evaluate until Thu Sep 15
🔥 ⚠️ Number of class refs 4 does not equal []
🔥 ⚠️ Could not locate descriptors section
🔥 As class ViewController has an @objc injected() method, HotReloading will perform a "sweep" of live instances to determine which objects to message. If this fails, subscribe to the notification "INJECTION_BUNDLE_NOTIFICATION" instead.
🔥 (note: notification may not arrive on the main thread)
🔥 Starting sweep [ViewController], []...
2022-04-07 10:37:36.857295+0800 Example[27267:5538503] Application tried to push a nil view controller on target <UINavigationController: 0x108019200>.
```

**Comment by johnno1962** [comment]
Hi, Thanks for the example project! It's always very helpful. Looks like I won't be able to fully support injection of Objective-C on a device. The nil view controller is from where you reference the class object when your code tries `XViewController.new` which hasn't been resolved correctly. If you can avoid statements like this or use `[NSClassFromString(@"ViewController") new]` instead it may work. The other warnings are related to this. Re breakpoints: LLDB wasn't written with injection in mind. Often breakpoints work for Swift but sometimes not.

**Comment by TMTBO** [comment]
![image](https://user-images.githubusercontent.com/2801001/162408547-a7ed76c0-cce7-43c5-8b16-a47a9a12f310.png)
Currently, I got this crash here. And I have not idea about that.
Maybe it's difficult to resolve this problem, right?

**Comment by johnno1962** [comment]
I'm sorry but you may have to stick to injection in the simulator. Injection on a device is still very much beta software  and it was not extensively tested with Objective-C. With your problem, in XViewController.m you had:
```
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
}
```
Commenting it out seemed to help but you will likely run into further problems further down the line as Objective-C makes it more difficult for the injection code than Swift when working on a device.
