### ISSUE TITLE
Could not locate compile command for storyboard

### ISSUE THREAD

**Issue by vualeks** [johnno1962/HotReloading#45]
Hi,

I've been struggling for last few days with storyboard hot reloading. I have an older test project where it works just fine, but now with a newly created one with Xcode 13.3 and only HotReloading added by SPM I can't make it work, always getting that error "Could not locate compile command for *storyboard*"

That generated command.sh doesn't give any output (you should also give that file +x permission when automatically created).

I thought that Xcode project format could be the reason so I've tried setting it to an older 9.3 compatible, but that didn't help also. I can see that no optimization is turned on (completely new test project, just HotReloading added, linker flags too, tried with and without that run script that starts daemon, injecting from code works ok) and the path should not be a problem, I guess. Do you have any suggestions how to investigate what could be the issue?

**Comment by johnno1962** [comment]
Hi, I hadn't checked storyboard injection with the newish standalone version of injection and have force pushed a commit ee923825f71339f930bd62c80f440d9c517512c6 that caters for it. Can you sync to this version and try again please? Remember to start a build instead of just saving the storyboard.

**Comment by vualeks** [comment]
Yep, now it works, thanks :)

In the meantime, I tried the old way by installing InjectionIII app (latest Github version) and it worked too.

**Comment by johnno1962** [comment]
Excellent!
