### ISSUE TITLE
EXC_BAD_ACCESS in SwiftSweeper

### ISSUE THREAD

**Issue by vualeks** [johnno1962/HotReloading#48]
Hi,

recently I started often getting this crash in line 224 of SwiftSweeper pretty randomly, don't know what triggers it.

`if let obj = $0.pointee {
                                    SwiftSweeper.current?.sweepInstance(obj)
                                }`

It was happening with Xcode 13.3 and 13.3.1 now, using HotReloading Swift package v4.3.15.

Do you have any suggetions what to try and how to investigate?

**Comment by johnno1962** [comment]
Hi, add an environment variable INJECTION_SWEEP_DETAIL to show objects as they are swept. The last class name printed is where the crash happens, which you should be able to exclude from the sweep using the environment variable INJECTION_SWEEP_EXCLUDE which is a regular expression.

**Comment by vualeks** [comment]
Nice, thanks!

It seems to be working, UITextChecker was the problem and with excluding it, no more crashes for now.

Maybe you should consider adding this to troubleshooting docs.

**Comment by johnno1962** [comment]
It's mentioned in the README.md
