### ISSUE TITLE
Visual Studio Code support?

### ISSUE THREAD

**Issue by markst** [johnno1962/HotReloading#49]
Hey @johnno1962, firstly thanks for all your work on HotReloading!

I stupidly made the issue on wrong repo here: https://github.com/jordansinger/SwiftUI-Kit/issues/46

Cheers for responding.

I wonder if you might offer some help as to how I can get HotReloading to work when debugging using vscode.

I've created a demo repo here: https://github.com/markst/hotreloading-vscode-ios
Hot reloading works great when running the generated Xcode project from Xcode.
However when launching the project from vscode, hot reloading doesn't work.

**Comment by johnno1962** [comment]
Hi, I'm not sure I can support you on that journey but looking at your repo, you don't seem to have added the HotReloading repo to your Package.swift or loaded the iOSInjection.bundle? You would normally do the latter here: https://github.com/markst/hotreloading-vscode-ios/blob/dev/Demo/Injection/Injection.swift#L11

**Comment by markst** [comment]
Ah the `Package.swift` is simply there for `SourceKit-LSP` support, which may not be necessary.

The `HotReloading ` is repo is added in the project.yml: https://github.com/markst/hotreloading-vscode-ios/blob/dev/project.yml#L6

As I mentioned - it is working fine when building & running in Xcode.

@johnno1962 That's fine, I wondered if something might be screamingly obviously as to why it may not work using `xcodebuild`

**Comment by johnno1962** [comment]
On second thoughts, there is very little prospect of VSCode support as InjectionIII needs to know where to find the build logs in order to work out how to recompile Swift source files. It might be possible to adapt it but the priority for now will be absorbing the changes that come with Xcode 14.

**Comment by markst** [comment]
Ah well in that case it seems that passing the Xcode DerivedData directory to `xcodebuild` does resolve my issue:
```
xcodebuild -scheme Demo -configuration Debug -sdk iphonesimulator -derivedDataPath ~/Library/Developer/Xcode/DerivedData -allowProvisioningUpdates ARCHS=arm64 <
```

**Comment by johnno1962** [comment]
Top marks for creativity there! Are you saying Injecting works now?

**Comment by markst** [comment]
![vscode-hotreload-2 2022-06-02 09_24_05](https://user-images.githubusercontent.com/274318/171602276-cd9be2ad-cb53-45b9-926b-a4dc534c1f79.gif)

**Comment by johnno1962** [comment]
Wow! No changes to HotReloading required? I'll put a pointer to your repo in the README. It may be using the build logs from when you were using Xcode but still great work.

**Comment by markst** [comment]
> It may be using the build logs from when you were using Xcode but still great work.

I thought that, but have deleted my `~/Library/Developer/Xcode/DerivedData` directory multiple times & still works.

@johnno1962 unless the logs are located elsewhere?

**Comment by johnno1962** [comment]
I'm a bit surprised to be honest HotReloading is finding them, but if it works it works ¯\\_(ツ)_/¯. Let me know how you get on and if it's stable I'll ad a note to the HotReloading README.

**Comment by markst** [comment]
I've added a section to README which explains how to overcome the `derivedLogs` location: 
https://github.com/markst/hotreloading-vscode-ios#support-hotreloading

**Comment by johnno1962** [comment]
This is awesome work! I''ve added a section to the README of HotReloading with a pointer to your project already. I'm wondering if it is possible to use a fixed DerivedData path without the Xcode hash? HotReloading should still find your logs and this would mean people can clone your project and use it without having to modify it.

**Comment by johnno1962** [comment]
In fact, it's already going to work isn't it? The Xcode hash you've entered is probably going to be used anyway. I feel a tweet coming on.

**Comment by markst** [comment]
Sort of related to https://github.com/johnno1962/InjectionIII/issues/388 then?

If using a DerivedData path without the hash, somewhere along the way the directory with the hash gets created:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/274318/171993160-d45abf5f-9157-402d-ae83-92a4bcdb80ed.png">

Far as I can tell, two reference to `DerivedData` logs are:
https://github.com/johnno1962/HotReloading/blob/main/Sources/HotReloading/StandaloneInjection.swift#L31
https://github.com/johnno1962/HotReloading/blob/main/Sources/injectiond/InjectionServer.swift#L362

**Comment by johnno1962** [comment]
I think the hashed path will get created just by viewing the project in Xcode without building it. This aside does injection work if leave off the hash? Perhaps it doesn't make much difference in the end.

**Comment by markst** [comment]
Nope, fresh `DerivedData` and hashed path gets created without ever opening Xcode. It get's created the first time saving after launching using iOS Debug.

Injection only works when passing hashed path to `xcodebuild -derivedDataPath`.

I'm happy with this setup, no real pressure to support custom derived path.

**Comment by johnno1962** [comment]
Interesting, but if people clone your project the hash will be different and it won't work for them which is a shame. I guess they could figure it out.

**Comment by markst** [comment]
I did make a start at building a swift package which could be used to generate the hash as part of the vscode environment. https://github.com/markst/xcode-project-hashes

I guess ideally I'd create a vscode extension which would automate the process: https://github.com/markst/hotreloading-vscode-ios/issues/4

**Comment by johnno1962** [comment]
Hey Mark, I'm happy you're still looking on this. I assume you found the [XcodeHash](https://github.com/johnno1962/InjectionIII/blob/main/InjectionIII/XcodeHash.m) implementation to work from. The other news is that I re-wrote The HotReloading Project to take out all the unnecessary code involved in working with the app that had accumulated over the years and is no longer required: https://github.com/johnno1962/InjectionLite. You may want to switch over to that? This code works out the correct build logs to work from by using the last modified one.

**Comment by markst** [comment]
had a real quick go integrating InjectionLite using Xcode in my demo project, but need to dig deeper as to why it's not working for me:

![2023-12-16 08-35-22 2023-12-16 08_37_40](https://github.com/johnno1962/HotReloading/assets/274318/df602bab-3d00-4ae5-a111-07921cd5ae36)

**Comment by johnno1962** [comment]
Hi @markst, Don't you just need an `@ObserveInjection var forceRedraw` at the end of your View struct to force the redraw? See: https://github.com/johnno1962/HotSwiftUI. To avoid crashes on more substantial edits you should also have a `.eraseToAnyView()` or `.enableInjection()` at the end of your view body to "erase" the concrete type returned so it doesn't change over an injection.

**Comment by markst** [comment]
Ah I was [previously](https://github.com/markst/hotreloading-vscode-ios/blob/dev/Main/Sources/ContentView.swift). 
The type erasing `enableInjection()` doesn't seem to be a part of InjectionLite?

**Comment by johnno1962** [comment]
It’s a part of `Inject` (or HotSwiftUI). Either way you need something in the view to observe the injection.

**Comment by markst** [comment]
thought I'd share this if it's of interest: https://github.com/markst/vscode-xcodegen-builder

**Comment by johnno1962** [comment]
Sounds Handy! Did you get your view refresh problems sorted out in the finish?

**Comment by johnno1962** [comment]
HI @markst, was wondering if you're waiting for xcodebuilds to build outside Xcode whether you'd be interested in https://github.com/johnno1962/xcodemake
