### ISSUE TITLE
reload not working. some issue related to ambiguity in choosing function

### ISSUE THREAD

**Issue by funactuator** [johnno1962/HotReloading#52]
The hot reload did not work. It shows the following output.
help out
<img width="1001" alt="Screenshot 2022-06-25 at 4 25 56 PM" src="https://user-images.githubusercontent.com/49099602/175770764-87f7d523-cb25-424e-8db8-545d04fa7a3b.png">
.

**Comment by johnno1962** [comment]
Hi, This warning comes from the system and is normal. You can ignore it. Have you implemented an `@objc func injected()` method to force a redraw of the display?

**Comment by funactuator** [comment]
yeah, I tried that too. It didn't work.

**Comment by johnno1962** [comment]
Have you tried the https://johnholdsworth.com/GettingStarted.zip project? Also, try moving your project out of the Documents, that can cause complications.
