### ISSUE TITLE
INJECTION_III_APP not defined

### ISSUE THREAD

**Issue by linlinyao1** [johnno1962/HotReloading#53]
when I tried add HotReload as a swift package in my own demo I found INJECTION_III_APP is not defined, thus device injection with InjectionIII app does not work

**Comment by johnno1962** [comment]
Hi, What was the exact error message? You should be able to add HotReloading as a Swift package to your app and then use the last binary 4.3.0 version of the InjectionIII app to manage the recompiles and inject if you set the user default the README mentions.

**Comment by linlinyao1** [comment]
from console log, i can see that HotReloading is trying to connect to localhost: 8899, but InjectionIII app on my mac is only listening to port 8898
I am using 4.3.0 download from github, and typed "defaults write com.johnholdsworth.InjectionIII deviceUnlock any
" which i checked "defaults read com.johnholdsworth.InjectionIII deviceUnlock" returns any

**Comment by linlinyao1** [comment]
I reinstalled InjectionIII app and now it works fine after config host name to my local ip address.
Thanks for this great project! 
going to close this issue
