### ISSUE TITLE
device injection build error in Xcode14

### ISSUE THREAD

**Issue by moonclock** [johnno1962/HotReloading#62]
Hi~ 
John, thanks for your work!  HotReloading is amazing, specially after supporting device injection.

but, I am trying use SPM to integrate HotReloading to my project,, but the project built failed, 
the error message like this:
.../SourcePackages/checkouts/HotReloading/Sources/injectiondGuts/SignerService.m:31:9: error build: 'system' is unavailable: not available on iOS
.../SourcePackages/checkouts/HotReloading/Sources/injectiondGuts/SignerService.m:31:9: error build: 'system' is unavailable: not available on iOS

Am I missing something in the setup?

Xcode version: 14.0
Device info: iPhone8P, iOS 16.0.2

my project && HotReloading
![图片](https://user-images.githubusercontent.com/12515349/196952457-f662215f-21ca-41a5-8c6c-218494ad4803.png)

error info:
![图片](https://user-images.githubusercontent.com/12515349/196947030-eecb9270-1ec0-49bd-bdf8-a964b27f9f0c.png)

**Comment by johnno1962** [comment]
Hi, looks like you added too many HotReloading products into your project. You should only add HotReloading as it shows on the project README. It seems to be building "injectiond" which will not build on iOS.

**Comment by moonclock** [comment]
> 

The answer is so fast, my project built success, I went to fix "HotReloading loaded but could not connect to my-MacBook-Pro.local", thanks john!
