### ISSUE TITLE
Problems using HotReloading as a Swift package

### ISSUE THREAD

**Issue by byohay** [johnno1962/HotReloading#67]
I added HotReloading as a Swift package for device Injection on an iOS device. Since it didn't connect, I tried to follow the instructions in the README:

> If your device doesn't connect, clone this project and configure your mac's WiFi IP address into the hostname variable in Package.swift. Then drag the clone onto your project to have it take the place of the configured Swift Package.

However it seems like a non trivial task to replace the Swift package with a local copy. Adding it as a local package doesn't work -There are no HotReloading prints at all (I think that this is caused by the fact that it won't let you select any products for a local package, as opposed to using a remote package). Changing the URL to my local copy in the `.pbxproj` file didn't work either. In fact the only thing that worked was to go to the `checkouts` folder of the app's derived data folder and replace the HotReloading package with a symlink to my local copy. 
Even after that, when changing code in HotReloading and compiling my app, the change wasn't reflected the first time I compiled the app and I had to try several times until it worked.

Questions:
1. Is there an easier way to use a local copy of HotReloading? If so, can you elaborate on it in the readme?
2. After I changed code in HotReloading, is there a way to guarantee that the new code will be used in the app when I compile it? If I were to use HotReloading as a subproject instead, Xcode would create a dependency between my app and HotReloading, which would guarantee that the new code of HotReloading is used by the app.
3. Assuming the answers to the previous questions is no, is there an alternative way to use device injection with HotReloading? If not, is it worth looking into?

P.S. Thanks for this really amazing project!!

**Comment by johnno1962** [comment]
Hi, I've pushed a change to the README to include a link to the Xcode documentation about using an editable local package so you can hard code the IP address of your machine. I can't do much more than that, I've found this mode of working a god-send developing injection and generally reliable. P.S. Thanks for the Thanks! It's appreciated.

**Comment by johnno1962** [comment]
I've pushed another section in the README about how to set the preference required for device injection. This is the more likely problem than not knowing the IP address which should be found using "multicast" but only if the app is listening. To make sure the preference has taken check your Mac is listening on port *.8899.
```
% netstat -an | grep LIST | grep 88
tcp4       0      0  127.0.0.1.8898         *.*                    LISTEN
tcp4       0      0  *.8899                 *.*                    LISTEN

**Comment by byohay** [comment]
Thanks for the quick reply! Indeed I missed the part where I just need to drag the local copy on top of the existing one.
But even after that I find it somewhat unreliable. At first I got this error:
![image](https://user-images.githubusercontent.com/15332602/205498940-0a1d76b7-ff01-4152-b9d7-766153347563.png)

I tried to compile a few times and then it worked without any change on my part (I also stumbled upon [this thread](https://developer.apple.com/forums/thread/687275) where all sorts of unrelated things solved this problem for people).

In addition, it seems like changes to `Package.json` (Albeit rare) aren't immediately effective. I had to wait a few seconds before running the app again, or I would not see the change ip address:
![image](https://user-images.githubusercontent.com/15332602/205605444-8e7a99c6-5fc5-49fe-8776-5ba6afbd10ca.png)
![image](https://user-images.githubusercontent.com/15332602/205605493-ec3ea887-ce3d-49e7-bd3a-c66eacef673d.png)

Maybe I just need to get used to the ergonomics of Swift packages :) 
If there isn't a quick solution here you can close the issue

**Comment by johnno1962** [comment]
Yeah, it's getting better but sometimes when you alter Package.swift dependancies you need to close and re-open the project. When you save Package.swift Xcode won't tell you but it is busy in the background updating which you'll only know if you try to build before it's finished. Swift Packages in Xcode have a learning curve but after things have settled down it should be plain sailing.
