### ISSUE TITLE
Updates overlap in UI

### ISSUE THREAD

**Issue by mattgabor** [johnno1962/HotReloading#71]
I have created a sample project to test this package out - the only custom code is pictured below. Whenever I make a change to the text both the previous and new text overlap each other - the old view is not being cleaned up properly

I am using the following to force a reload:
```
extension UIViewController {
    @objc func injected() {
        viewDidLoad()
    }
}
```

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/5590876/215963461-eadfc46e-9898-4b8b-9975-7a7a7c43b384.png">

Version 4.9.6
MacOS Ventura 13.1 (22C65)
Xcode 14.2.0

**Comment by johnno1962** [comment]
Hi, You probably need to restructure your code into a separate `confirgureView()` method which is called from the `injected()` method that removes all subViews before adding the label again otherwise they will accumulate.
