### ISSUE TITLE
class category injection failed on device

### ISSUE THREAD

**Issue by qmkCamel** [johnno1962/HotReloading#72]
When I inject in a class category, found it couldn't get a class in `func extractClasses`.
So, is this a known issue? 
Or it isn't a recommend way?

**Comment by johnno1962** [comment]
Ha, It's a known potential issue, the category would be in a separate file from the class right? Is this on device? If you roll me a small example project I can look at it for you. There should be a way if you think it's important. I'm a little surprised the category methods aren't returned by `class_copyMethodList()`.

**Comment by qmkCamel** [comment]
Yes, it's on device. Here is the demo. You can check the `DemoViewController+Debug`.
I debug the `HotReloading`, and found it may not because of the `class_copyMethodList()`.
The below function return [], so it didn't  execute the following code.
``` swift
@objc override open func extractClasses(dl: UnsafeMutableRawPointer,
                                       tmpfile: String) throws -> [AnyClass] {
        var classes = [AnyClass]()
        SwiftTrace.forAllClasses(bundlePath: searchLastLoaded()) {
            aClass, stop in
            classes.append(aClass)
        }
        if classes.count > 0 && !SwiftTrace.deviceInjection {
            print("\(APP_PREFIX)Loaded .dylib - Ignore any duplicate class warning ⬆️")
        }
        return classes
    }
```
[hot_reload_demo 2.zip](https://github.com/johnno1962/HotReloading/files/10812983/hot_reload_demo.2.zip)

**Comment by johnno1962** [comment]
Thanks for the project but there is something odd about it which I can't figure out and be able to debug it. Anyways.. Are you absolutely sure categories aren't injecting? When you load a category the new implementation is always updated on the class, in fact, this is how the very original version of injection worked. The injection code doesn't need to do anything.

**Comment by qmkCamel** [comment]
For more information, I use the build phase to trigger InjectionServer instead of the InjectionIII App on the github.  If I inject in a category `DemoViewController+Debug`, can't get a class like beblow.
![image](https://user-images.githubusercontent.com/5952752/220912292-20ce7ad0-666d-49b7-90f7-7044dc367179.png)
What else can I provide to help confirm the case?

**Comment by johnno1962** [comment]
You won't get the class but categories inject automatically themselves as part of being dynamically loaded. Edit the print message in your category and verify if it is being updated when you call it (it was for me in my test project). Injection has to swizzle classes as there can be instances outstanding on the class with their own "isa" pointing to the oldClass..

**Comment by qmkCamel** [comment]
Got it, I was misled by the following message 😅. 
`🔥 ⚠️ Injection may have failed. Have you added -Xlinker -interposable to the "Other Linker Flags" of the executable/framework? ⚠️
`
Thanks for your patience.

**Comment by johnno1962** [comment]
Nothing is worse than a bogus message... I've pushed a commit which should silence it when there are categories present.
