### ISSUE TITLE
Some questions about the implementation.

### ISSUE THREAD

**Issue by qmkCamel** [johnno1962/HotReloading#73]
The project HotReloading 's Contents should be modify from InjectionIII ?
<img width="393" alt="image" src="https://user-images.githubusercontent.com/5952752/221401255-44397bc6-6c31-4509-b60c-97f14b1bc0c2.png">
I tried build the InjectionsIII, copy the nib files in the InjectionsIII app, but it didn't work.
I am curious how it works. Thanks.

**Comment by johnno1962** [comment]
Hi, those were copied once when I created the HotReloading project so I'm less concerned about their being up to date and they are only used by the daemon (Build Phase) which I phased out. It was time for a clean out of all the code that has accumulated over the years and there is a new Swift Package, standalone implementation [InjectionLite](https://github.com/johnno1962/InjectionLite) which is a lot easier to follow through what it is up to if you're interested.
