### ISSUE TITLE
Crasing in SwiftInjection

### ISSUE THREAD

**Issue by vualeks** [johnno1962/HotReloading#74]
Hey,

at first it was occasional, now almost every other app build/start, I get crashes in SwiftInjection.swift
<img width="1565" alt="Screenshot 2023-03-10 at 22 17 32" src="https://user-images.githubusercontent.com/13743682/224430148-30d118c3-e587-4860-b1f5-0d407c342e16.png">
Could it be related to some unit test files are not building at this moment? I cann't figure out what could trigger this. Updated to latest version 4.10.3 and latest InjectionIII app too, didn't help.

**Comment by johnno1962** [comment]
Do you have "Enable TDD" selected? Are you wanting to use the inject test feature? If not you may want to try the new simpler version https://github.com/johnno1962/InjectionLite which no longer needs the app running.

**Comment by vualeks** [comment]
I don't want to use inject test feature (didn't know it exists :D ), just main code injection. I just tried with Enable TDD with Injection app, same result, then removed the app, added InjetcionLite and also the same crash at the same place.

**Comment by vualeks** [comment]
I have also fixed the unit tests, they build correctly now, but that didn't help anyway.

**Comment by johnno1962** [comment]
newClass should be the class you're injecting. What can you tell me about it? Is it a generic or inherit from one?

**Comment by vualeks** [comment]
Yeah, it inherits from a generic one in this case that I just tried.

`class SomeCoordinator: NavigationCoordinator<SomeRoute>`

**Comment by johnno1962** [comment]
I've pushed a new branch `generics-tests` you could sync to which should avoid this problem. Let me know how you get on.

**Comment by vualeks** [comment]
There is a different error now, I've tried with changes in the same class as before
<img width="1503" alt="Screenshot 2023-03-11 at 16 32 08" src="https://user-images.githubusercontent.com/13743682/224493281-8550a0c1-a742-488e-b575-79ba6b14e1c7.png">

**Comment by johnno1962** [comment]
I've pushed another commit avoiding the newly loaded class in this test. It's strange this hasn't been reported before.

**Comment by vualeks** [comment]
Still looks the same, hope the error output helps
<img width="1511" alt="Screenshot 2023-03-11 at 16 50 18" src="https://user-images.githubusercontent.com/13743682/224494385-a3cec79a-3f96-40e9-a6b5-c24e600ba0ec.png">

**Comment by johnno1962** [comment]
Your output helps a lot. Seems like your class doesn't inherit from NSObject anywhere so a lot of Objective-C run time capabilities surfaced through methods like isSubClass: and superclass are not available. I'll have to look into what can be supported. Are you able to inherit NSObject somewhere to prove the theory? Are you sure you synced to the last commit?

**Comment by vualeks** [comment]
Yep, it recompiles and injects ok now, but those classes are part of a library so I had to edit inside it. Anyway, now I at least know what are some additional caveats.

**Comment by johnno1962** [comment]
Yes, I imagine most people are injecting UIViewControllers where NSObject comes for free. Thanks for taking the time to report this. I'll see if I can replicate and find a solution but it might be tricky. Seems like I need to find an alternative for `superclass` and `isSubclass` not dependant on Objective-C.

**Comment by vualeks** [comment]
Thank you for your work on HotReloading, still amazing with all the limitations!

Btw, the library in place was https://github.com/QuickBirdEng/XCoordinator so you can see there all the inheritance and from what they started so that you can replicate it.

**Comment by johnno1962** [comment]
Thanks, I chip away at the limitations as people report them. I've pushed another commit to the HotReloading branch which moves further away from the runtime apis. Are you able to do a quick check to see if there is anything else that your class trips up?

**Comment by vualeks** [comment]
Pulled and tried again, still looks the same as the last crash

**Comment by johnno1962** [comment]
Are you sure you're refreshing the branch? It can't look the same as the code has changed. Try "Reset Package Cache" or "Update Package". The commit is d16e554a4b6dc41742e19242b8c1b30d4cff873a which you can also enter.

**Comment by vualeks** [comment]
Yeah, you were right, I did update packages and clean build and now got different error
<img width="1502" alt="Screenshot 2023-03-11 at 19 07 01" src="https://user-images.githubusercontent.com/13743682/224504694-cf4fd5aa-70ac-400c-8762-8ba5469637fd.png">

**Comment by johnno1962** [comment]
I've pushed another commit. I thought === would be safer but I've seen it fail before. Can you try f67d5a60b2616cb1f2f38305365d5723d0599fb7 please?

**Comment by vualeks** [comment]
Aha, it seems to be working now! One thing I've noticed is that there are now lots of some gunzip/grep commands going on in the first recompile, but later it injects much faster.

**Comment by johnno1962** [comment]
Great, happy to hear it. The greps happen the first time you inject a particular file and after that it is cached in memory. You obviously have quite a large project if you're noticing that. I've pushed another commit which uses the disk cache more if you want to try it. 46b68ddf71c7e8293ec848cf086d12f96568db2a

**Comment by vualeks** [comment]
Tried it, no big difference, but that's ok. Important thing is that now it works. Thanks

**Comment by johnno1962** [comment]
Strange, it should have remove the initial scan if you're injecting a file that you've injected before. I'll leave the change in as it should fail-safe and delete the cache entry if a compile fails. Thanks again for raising this issue. This has been one of the more useful ones! Removing those last vestiges of dependency on the Objective-C runtime was worth it. Let me know if anything else crops up otherwise I'll merge the branch later today.

**Comment by vualeks** [comment]
Actually, it does improve compiling the first time, I guess I didn't apply the update properly again. After removing and adding the package, and clean build now I see it injects faster.

**Comment by johnno1962** [comment]
I wondered about that... The easiest way to flush the package cache and be sure you have the right version is to select the "commit" 326a5e6a4a7e475a132e271fab45f57a49f40c7e as you add the package instead of the branch or tag. I've pushed another change reverting to using class_getSuperclass() which seems to be a generic-proof api (it doesn't do much). In the new version you can now add a `@objc func injected()` method to classes that don't inherit from NSObject and have them called on injection. See how you go.

**Comment by johnno1962** [comment]
I've merged and tagged this now as 4.11.0. If you could give it a try and let me know if there are any problems I'd appreciate it. Thanks again for taking the time to raise this issue and try the various versions!
