### ISSUE TITLE
Is there anyway to re-compile a file only when cmd + s ?

### ISSUE THREAD

**Issue by qmkCamel** [johnno1962/HotReloading#76]
The mac app will re-compile the file whenever the file change, is there anyway to re-compile a file only when cmd + s ?

**Comment by johnno1962** [comment]
Hi, You can turn off the "File Watcher" from the app menu. Then it will only inject when you type control-=.

**Comment by qmkCamel** [comment]
Got it. Control-= only works in InjectionIII app.

**Comment by johnno1962** [comment]
Without writing an Xcode plugin, that's just how it is I'm afraid.
