### ISSUE TITLE
Will the DDHotKey affect the file watch ?

### ISSUE THREAD

**Issue by qmkCamel** [johnno1962/HotReloading#80]
I use the DDHotKey  with command + s  in HotReloading as a package, but found it will affect the File Watcher, it cann`t get the callback when command + s triggered. I didn`t figure out how it happed.

**Comment by johnno1962** [comment]
Not sure I understand what you're saying. DDHotKey is compiled into the app. It won't work using HotReloading alone which relies on calling the FileSystemEvent api from inside the simulator so your only option is cmd-s.

**Comment by qmkCamel** [comment]
I forked a HotReloading and add the DDHotKey in it, and set a cmd + s hotkey. But when I trigger the cmd + s, found the file watcher didn`t get a callback, only the hotkey action triggerd.

**Comment by johnno1962** [comment]
I'm surprised DDHotKey works inside the simulator. It uses an old "Carbon" api so the chances of it working are very low. I'll have to leave you to work this one out.

**Comment by qmkCamel** [comment]
I tried it on device. And I will find a way to work it out. Thanks~

**Comment by qmkCamel** [comment]
The DDHotKey with cmd + s will delay the FSStreamEventCallback about 10 - 15 seconds on device.

**Comment by johnno1962** [comment]
I'm not sure I understand what you're up to. How do you mean "on device"? How could it work "on device"? Have you tried using the existing hot key of control-=? instead?
