### ISSUE TITLE
Cannot use HotReloading with Other debug configurations (ex. Dev, Test Configuration)

### ISSUE THREAD

**Issue by gatherheart** [johnno1962/HotReloading#82]
Hello, I have a question.
When I use the HotReloading package with other configurations, the Injection does not start.
If I use a scheme that has "Test Configuration", I found that `BundleInjection` is not loaded and Injection doesn't start.
The "Test Configuration" is just a copy of "Debug Configuration" and only the name is different.

You can reproduce this situation even with [SwiftUI-Kit](https://github.com/johnno1962/SwiftUI-Kit) after adding a new configuration and a new scheme using the new configuration.

Is there any way to use other configuration other than `Debug`? (Of course, except `Release`)
Thank you.

<br>
<br>

<img width="814" alt="image" src="https://github.com/johnno1962/HotReloading/assets/40990613/4463ed9c-8ecc-4ea1-bddd-d24d470fa83e">

<br>
<br>

Related Issue:
https://github.com/johnno1962/HotReloading/issues/57#issuecomment-1221613812

**Comment by johnno1962** [comment]
Hi, are you sure your new configuration defines `DEBUG` for the compiler?
<img width="643" alt="image" src="https://github.com/johnno1962/HotReloading/assets/1786033/caa79d26-74fb-4ce4-951f-6e8ca0d9f5c7">

**Comment by gatherheart** [comment]
Hi @johnno1962 Thank you for your response.

Of course, I added it. 
I just copied the default Debug configuration existing at the "SwiftUI Kit" project.

If you want the sample project, I can attach it.

<img width="709" alt="image" src="https://github.com/johnno1962/HotReloading/assets/40990613/e2af02de-129d-4f2a-a556-09d608a53acb">

**Comment by johnno1962** [comment]
Well, I guess it's just Xcode having a bad day. The other alternative is to download the app and use one of the prebuilt bundles (it's all the same code) provided you're not trying to inject on a device.
```Swift
#if DEBUG
Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle")?.load()
//for tvOS:
Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/tvOSInjection.bundle")?.load()
//Or for macOS:
Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/macOSInjection.bundle")?.load()
#endif
```
I'll see if I can replicate it and get to the bottom of what's going on.

**Comment by johnno1962** [comment]
This may be a silly question but how do you create a new configuration again?

**Comment by gatherheart** [comment]
Okay, Thank you.
I'll use the prebuilt bundle until figuring it out.

In the project setting, there is a "Configurations" section, and the + button is for making new configurations.

<img width="1119" alt="image" src="https://github.com/johnno1962/HotReloading/assets/40990613/a7a9aa08-dbe1-4453-834c-d00aa47e44ec">

**Comment by johnno1962** [comment]
Thanks for that, very strange though, I can't replicate the problem. Any chance of a small test project?

**Comment by gatherheart** [comment]
Did you change your scheme's configuration also?
If it uses Debug configuration, the problem might not happen

If you are using a scheme with debug configuration, Could you change the configuration into a new one?
Thanks for checking.

<img width="533" alt="image" src="https://github.com/johnno1962/HotReloading/assets/40990613/b694fbe1-27f0-4d6d-8783-2ec01f16b723">

<img width="940" alt="image" src="https://github.com/johnno1962/HotReloading/assets/40990613/98f4c9ee-9d65-4fbb-bd85-bc9990850821">


<br>
<br>

Here is the sample project.
[TestHotReload.zip](https://github.com/johnno1962/HotReloading/files/11686493/TestHotReload.zip)

**Comment by gatherheart** [comment]
I also try to find out what is the problem.
IMO, There might be some branches using the "Debug"  configuration name.

**Comment by johnno1962** [comment]
Thanks for the sample project. It's an Xcode problem where it's not building the HotReloading package with -DDEBUG etc for anything other than a `Debug` configuration if you look at the build log. Seems like something is hard coded somewhere. I tried fixing it by adding the options to the Package.swift and all sorts of other problems came up. Perhaps you could file a radar for me?

**Comment by gatherheart** [comment]
Okay. I will report it through Feedback Assistant.
Thanks for finding out sincerely.

I'll report it and keep track of what's going on in this thread.

**Comment by johnno1962** [comment]
Thanks for that and reporting this issue. It's interesting to know but I'm afraid there isn't much I can do about it. Can you put a link to this thread in the FB and post it's number here and perhaps I can bend someone's ear though I imagine they are pretty busy this time of year..

**Comment by johnno1962** [comment]
P.S. Seems like it compiles your packages for debugging (which is required for HotReloading to be enabled) if your configuration name _contains_ the string `Debug`. Rename your config to "Test Debug" and it should work. Not exactly anticipated behaviour but difficult to think of what else they could have done.
