### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by ljw215** [johnno1962/HotReloading#87]
InjectionClient/Could not connect: Connection refused
🔥 ⚠️ HotReloading loaded but could not connect to 172.22.155.24. Is injectiond running?

**Comment by johnno1962** [comment]
You're running on a real device now? Have you followed the instructions about downloading the app, setting a default and running it from the README of this project?

**Comment by ljw215** [comment]
yes, I do

**Comment by johnno1962** [comment]
You need to get to the point where your iPhone client connects to the InjectionIII app (server). This is a little tricky and there are some notes in the README about how to check the various components are in place.

**Comment by ljw215** [comment]
~ /Library/Containers/com.johnholdsworth.InjectionIII/Data/Library/Preferences/com.johnholdsworth.InjectionIII.plist  ，this directory was not found

**Comment by johnno1962** [comment]
OK, that just means you haven't used the App Store version of the app in the past. Don't worry.

**Comment by ljw215** [comment]
Should I download from App strore? I'm now gitup release

**Comment by ljw215** [comment]
I am now the latest version of githup release

**Comment by johnno1962** [comment]
Injection on a device only works with the GitHub release.

**Comment by ljw215** [comment]
thank you, now is GitHup ,No more of the above errors, now report this error：
dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib, 0x0002): tried: '/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib), but incompatible platform (have 'iOS-sim', need 'iOS'))
🔥 ⚠️ Injection error: Error Domain=SwiftEval Code=-1 "dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib, 0x0002): tried: '/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib), but incompatible platform (have 'iOS-sim', need 'iOS'))" UserInfo={NSLocalizedDescription=dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib, 0x0002): tried: '/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib), but incompatible platform (have 'iOS-sim', need 'iOS'))}

**Comment by ljw215** [comment]
🔥 ***** Tests bundle wasn't found - did you run the tests target before running the application?
🔥 Loading .dylib ...
🔥 ⚠️ dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib, 0x0002): tried: '/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib), but incompatible platform (have 'iOS-sim', need 'iOS'))
🔥 ⚠️ Injection error: Error Domain=SwiftEval Code=-1 "dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib, 0x0002): tried: '/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib), but incompatible platform (have 'iOS-sim', need 'iOS'))" UserInfo={NSLocalizedDescription=dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib, 0x0002): tried: '/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/690748B1-E457-4E73-A753-0EFCFC6C5549/tmp/eval101.dylib), but incompatible platform (have 'iOS-sim', need 'iOS'))}

**Comment by ljw215** [comment]
It has been solved, thank you. When using HotReloading, boundle cannot be loaded at the same time

**Comment by johnno1962** [comment]
Great, it's a bit tricky getting up and running but once it is you should be OK. If in doubt, do a "Clean Build Folder" when switching configuration.
