### ISSUE TITLE
lopen() error: dlopen(/private/var/mobile/Containers/Data

### ISSUE THREAD

**Issue by ljw215** [johnno1962/HotReloading#89]
The following error was reported, and I did not run it again many times, nor did I clear DeriveData
🔥 Loading .dylib ...
🔥 ⚠️ dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/1E8E5159-E037-4069-B520-2DE8ACBFE59F/tmp/eval104.dylib, 2): Symbol not found: __OBJC_PROTOCOL_$_TalosPopUpFrameBusinessProtocol
  Referenced from: /private/var/mobile/Containers/Data/Application/1E8E5159-E037-4069-B520-2DE8ACBFE59F/tmp/eval104.dylib
  Expected in: flat namespace
 in /private/var/mobile/Containers/Data/Application/1E8E5159-E037-4069-B520-2DE8ACBFE59F/tmp/eval104.dylib
🔥 ⚠️ Loading .dylib has failed, This is likely because Swift code being injected references a function using a default argument or a member with access control that is too restrictive or perhaps an XCTest that depends on code not normally linked into your application. Rebuilding and re-running your project (without a build clean) can resolve this.
🔥 ⚠️ Injection error: Error Domain=SwiftEval Code=-1 "dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/1E8E5159-E037-4069-B520-2DE8ACBFE59F/tmp/eval104.dylib, 2): Symbol not found: __OBJC_PROTOCOL_$_TalosPopUpFrameBusinessProtocol
  Referenced from: /private/var/mobile/Containers/Data/Application/1E8E5159-E037-4069-B520-2DE8ACBFE59F/tmp/eval104.dylib
  Expected in: flat namespace
 in /private/var/mobile/Containers/Data/Application/1E8E5159-E037-4069-B520-2DE8ACBFE59F/tmp/eval104.dylib

**Comment by johnno1962** [comment]
Hi, that seems to be on a device. I guess the first question to ask is: does it work in the simulator?

**Comment by ljw215** [comment]
The simulator is OK, and now it's OK again. I don't know what's going on, but  report an error when modifying Swift files，oc files is ok：
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator are case sensitive.
4. The modified source file is not in the current project.
5. The source file is an XCTest that has not been run yet.
6. Xcode has removed the build logs. Edit a file and re-run
