### ISSUE TITLE
Cannot reload on M1: Mac os Sonoma prevents InjectionIII from accessing data

### ISSUE THREAD

**Issue by oryonatan** [johnno1962/HotReloading#90]
Hi there, and thanks again for fixing my previous issue 
https://github.com/johnno1962/HotReloading/issues/88

The previous fix implemented in 4.7.5 solved the  “eval101.dylib” message issue, however recently I've upgraded to MacOS Sonoma, and now, again I cannot use InjectionIII on Apple Silicon.

Seems like a new sandbox mechanism prevents injection from accessing files, and whenever I change a source file, I am getting this message:
![image](https://github.com/johnno1962/HotReloading/assets/1219975/f09ee847-e4e9-4fd3-9607-c16a255226ba)

Pressing Allow doesn't help, the pop-up just appear again and again.

I've seen a thread about a similar issue in the Zoom app forums, see https://community.zoom.com/t5/Meetings/Zoom-would-like-to-access-data-from-other-apps-macOS-14-Sonoma/m-p/140967.
It seems like the correct solution will be to allow full disk access to InjectionIII. However, setting this in the security preferences of the Mac does not help. (I suspect that the InjectionIII executable that causes the OS to show this message is not the same one as the one the OS grants the permissions, but I am not sure about it.)

**Comment by johnno1962** [comment]
Hi, thanks for letting me know about this. I didn't notice this in any of the Betas. Are you using the HotReloading project still or is this "the App". Have you tried quitting the app and using "standalone" injection by just loading the bundle (which won't work for Device or iOS on Mac)? Is this one of the binary releases from GitHub for the Mac App Store version?

**Comment by oryonatan** [comment]
I am using HotReloading in the `SwiftUI Kit` app with HotReloading checked out to `* 5427424 - (10 days ago) iOS running on Mac II - John Holdsworth (HEAD, origin/main, origin/HEAD)`

However, I just tried this again and now it started working ... not sure what happened exactly, maybe an XCode reset or something?

Closing the issue for the time being, I will open again if I find out when this is reproduced and when not.

**Comment by johnno1962** [comment]
Very Strange. Do let me know if you see the message again; That wouldn't be a good look!
