### ISSUE TITLE
 Loading .dylib has failed, This is likely because Swift code being injected references a function using a default argument or a member with access control that is too restrictive or perhaps an XCTest that depends on code not normally linked into your application. Rebuilding and re-running your project (without a build clean) can resolve this.

### ISSUE THREAD

**Issue by zerocc2014** [johnno1962/HotReloading#93]
Loading .dylib has failed, This is likely because Swift code being injected references a function using a default argument or a member with access control that is too restrictive or perhaps an XCTest that depends on code not normally linked into your application. Rebuilding and re-running your project (without a build clean) can resolve this.
 
 use [HotReloading](https://github.com/johnno1962/HotReloading)  SPM in .xcworkspace cocopods project

**Comment by johnno1962** [comment]
Hi, Is this Swift or Objective-C? Can you tell me the name of the symbol that is not defined?

**Comment by zerocc2014** [comment]
> Hi, Is this Swift or Objective-C? Can you tell me the name of the symbol that is not defined?

my project Swift and Objective-C，symbol not found in flat namespace '_xxx';

`
typedef NSString *URLConstString;
extern a URLConstString xxx;
URLConstString const xxx = @"yyyyy";
`

**Comment by zerocc2014** [comment]
> Hi, Is this Swift or Objective-C? Can you tell me the name of the symbol that is not defined?

my project Swift and Objective-C，symbol not found in flat namespace '_xxx';

`
typedef NSString *URLConstString;

extern a URLConstString xxx; 

URLConstString const xxx = @"yyyyy";
`

**Comment by zerocc2014** [comment]
> Hi, Is this Swift or Objective-C? Can you tell me the name of the symbol that is not defined?

dlopen(/..path/tmp/eval101.dylib, 0x0002): symbol not found in flat namespace '_xxx'

**Comment by johnno1962** [comment]
Strange, can you remove the "const"?

**Comment by zerocc2014** [comment]
> Strange
above i write error，original like this
typedef NSString *URLConstString;

extern URLConstString const xxx;

URLConstString const xxx = @"yyyyy";

**Comment by johnno1962** [comment]
I'm not sure what the problem is. If you can't inject files that refer to this definition you could consider creating a class method to access the variable.

**Comment by zerocc2014** [comment]
> I'm not sure what the problem is. If you can't inject files that refer to this definition you could consider creating a class method to access the variable.

thx， I use demo test inject success，but company project is fail.

**Comment by johnno1962** [comment]
Not much more I can say here. When referring  to a particular symbol gives you problems dynamically loading you have to explore ways to avoid referring to that symbol directly in the file being inject for example by using a class method.
