### ISSUE TITLE
Hot reloading doesn't work in framework targets when a custom folder name is used for derived data

### ISSUE THREAD

**Issue by FelixLisczyk** [johnno1962/HotReloading#95]
I'm using the new `INJECTION_DERIVED_DATA` environment variable (https://github.com/johnno1962/HotReloading/issues/94#issuecomment-2118351474) and have noticed that hot reloading doesn't work in framework targets if Xcode uses a custom folder name for derived data. For example "Build" instead of "DerivedData":

![Screenshot 2024-06-06 at 13 28 01](https://github.com/johnno1962/HotReloading/assets/5102728/a5cb95d7-a66b-4cda-9d57-40711593f587)

I've created a sample project (attached below) that contains an iOS app and a framework target. You should be able to reproduce the issue as follows:

1. Download and open the sample project
2. Set the derived data path in Xcode settings to "Relative" but keep the default folder name (DerivedData)
3. Run the Xcode project in the iOS simulator
4. Verify that changes in `ContentView` (part of the iOS app) are hot reloaded (e.g. change text)
5. Verify that changes in `FrameworkView` (part of the framework) are hot reloaded (e.g. change color)
6. Change the derived data folder name in Xcode from "DerivedData" to "Build"
7. Update the `INJECTION_DERIVED_DATA` environment variable in the run scheme to `$(SRCROOT)/Build`
8. Verify that changes in `ContentView` are hot reloaded
9. Verify that changes in `FrameworkView` are hot reloaded

In my testing, the last step doesn't work. HotReloading prints the regular console messages, but changes from `FrameworkView` are not reflected in the simulator.

Please let me know if you have any questions or trouble reproducing the issue. Thank you very much! 😊

[HotReloadingExample.zip](https://github.com/user-attachments/files/15614581/HotReloadingExample.zip)

**Comment by johnno1962** [comment]
Hi Felix, thanks for the example project. That's always a help. Depending on Xcode 16 I'm likely to release a refresh of the project that works with your example project and a relative DD path early next week.

**Comment by johnno1962** [comment]
Hi, I've released the new version of Injection, https://github.com/johnno1962/InjectionNext if you want to give it a try and report back. It's mostly the same as previous versions of Injection except you need to run Xcode from inside the app so it can discover information about how to build files exactly.

**Comment by FelixLisczyk** [comment]
Thank you very much for releasing this new tool! I've followed the steps from the `README.md` and made the following changes to my example project:

1. Removed `HotReloading` and `Inject` dependencies
2. Added `InjectionNext` as a dependency to both the app and framework targets
3. Disabled the environment variables `INJECTION_STANDALONE` and `INJECTION_DERIVED_DATA`

This caused the build process in Xcode 15.4 to fail with the following linker error:

```
Undefined symbols for architecture arm64:
  "nominal type descriptor for DLKitD.ImageSymbols", referenced from:
      _symbolic _____5image_SayyXlXpG3old_AC3newShySSG8genericst7classestSg 6DLKitD12ImageSymbolsC in InjectionNext.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've managed to work around this issue by removing `InjectionNext` from the framework target and re-adding the `Inject` dependency. After running the app, I'm observing the same behavior as before:

| Derived data location      | Change in app target | Change in framework target |
|----------------------------|----------------------|----------------------------|
| Default                    | ✅                    | ✅                          |
| Project Folder/DerivedData | ✅                    | ✅                          |
| Project Folder/Build       | ✅                    | ❌                          |

I attach the updated sample project: 
[HotReloadingExample.zip](https://github.com/user-attachments/files/15786753/HotReloadingExample.zip)

One other question: Is the new `InjectionNext` tool only compatible with Xcode? I'm asking because my code changes in external editors like VS Code were not detected at all, even when running the app through Xcode. I'm trying to avoid Xcode as much as possible and have developed my own toolchain around VS Code and the Xcode Command Line Tools. It would be great if hot reloading was still available in other code editors as well. Thank you so much for your great work! 👍

**Comment by johnno1962** [comment]
Thanks for getting back so quickly. I've not seen the error you're reporting but had to do the following:
* Added InjectionNext to only the HotReloadingExample target
* Added Inject as a direct dependency to HotReloadingExample and add HotReloadingExampleKit link with Inject.

Perhaps it's best to leave Inject as a separate dependency rather than trying to import it for people which seems to fail.
What I hadn't anticipate is you were using VScode in which case this new version isn't for you as it is "integrated" with the connection to the Xcode app and uses that for file watching which should be more reliable. If you have any problems using the old version of the app with Xcode 16 (other than this one you reported) let me know and I'll go ahead and test that now.

**Comment by FelixLisczyk** [comment]
Thanks for the info! I can work around the original issue in my post by setting the derived data path in Xcode settings to "Relative" -> "DerivedData". This allows me to continue using the `HotReloading` and `Inject` packages with my current setup. I just have to update a few `.gitignore` files and should be good to go.

I've tried my original sample project with the Xcode 16 beta and noticed that hot reloading doesn't work at all, unfortunately. Even when modifying `ContentView` in Xcode directly with the "Default" derived data location. Here is the console output:

```
InjectionClient/Could not connect: Connection refused
🔥 Unable to connect to InjectionIII app, falling back to standalone HotReloading.
<SwiftEval: 0x102b08270>.deinit()
🔥 Standalone HotReloading available for sources under ["/Users/felix"]
UIAccessibility Error adding method that already exists. It's likely this class is being installed as a safe category twice -[_UIFloatingTabBarPageButton isAccessibilityElement]
UIAccessibility Error adding method that already exists. It's likely this class is being installed as a safe category twice -[_UIFloatingTabBarPageButton accessibilityTraits]
UIAccessibility Error adding method that already exists. It's likely this class is being installed as a safe category twice -[_UIFloatingTabBarPageButton accessibilityLabel]
UIAccessibility Error adding method that already exists. It's likely this class is being installed as a safe category twice +[_UIFloatingTabBarPageButton safeCategoryBaseClass]
🔥 Compiling /Users/felix/Downloads/HotReloadingExample/HotReloadingExample/ContentView.swift
🔥 Selecting Xcode /Applications/Xcode-16.0.0-Beta.app/Contents/Developer
🔥 Loading .dylib ...
🔥 Injected type #1 'HotReloadingExample.ContentView'
🔥 ⚠️ Injection may have failed. Have you added -Xlinker -interposable (without double quotes and on separate lines) to the "Other Linker Flags" of the executable and frameworks? ⚠️
```

The linker flags are still set correctly. Should I create a new issue for this?

**Comment by johnno1962** [comment]
I've been able to get injection to not work at all using a custom "DerivedData" path but "Relative" works for me, even with the app under Xcode 16. I can't imagine why that would be but it seems to be something specific to the new Xcode (ignoring options?) All in all, the day after a new Xcode release that things can work is good news. Sorry if the new version of Injection isn't for you but I can quite understand if you are "over Xcode".

**Comment by FelixLisczyk** [comment]
Funny enough, I've just noticed that changes in `FrameworkView` (framework target) are hot reloaded when running the app with Xcode 16 beta. Only changes in `ContentView` (app target) are ignored. So it's basically the opposite of my original issue. 😅 I've tested my original sample project with derived data locations "Default" and "Relative" -> "DerivedData".

**Comment by johnno1962** [comment]
All very odd. My money is on this being an issue with Xcode remembering to add the -interposbale flag to the link. In fact, if you look at the build logs the `-Xlinker -interposable` is missing from the link of the main app so SwiftUI won't be able to inject. We'll have to see if this comes right with future betas or it's radar time. Perhaps they think you shouldn't be adding `-interposable` to more than one target??

**Comment by johnno1962** [comment]
FB13842124

**Comment by johnno1962** [comment]
I've found out why the problem was here if you want to try Xcode 16 again. I've also uploaded a new release candidate resolving the same problem if you want to try it out with "injection classic"/VSCode.

**Comment by FelixLisczyk** [comment]
Thank you very much for the update! I can confirm that hot reloading now works with Xcode 16 beta and my VS Code setup. 👍 I haven't tested a custom derived data folder name again since I've now migrated all my projects to use `$(SRCROOT)/DerivedData`.

**Comment by johnno1962** [comment]
Excellent and thanks for your example project! It was the perfect tool to work out what Apple was up to.
