### ISSUE TITLE
Is it possible to integrate HotReloading by using CocoaPods?

### ISSUE THREAD

**Issue by ShengfengLee** [johnno1962/HotReloading#96]
We have a project that involves a mix of Objective-C and Swift. We integrate all the components using CocoaPods. Do we have any plans to integrate CocoaPods?

**Comment by johnno1962** [comment]
I'm afraid not, the HotReloading package is rather complex. Can you not use CocoaPods and SPM side by side?

**Comment by xing3523** [comment]
@johnno1962 Hi, HotReloading is a very useful tool and I have been using it, Thank you very much. However, SPM is very slow to download in some scenarios, so our project also has the same requirement. I tried to encapsulate them into frameworks and then use them through CocoaPods, which is feasible. I wanted to submit a PR here, but considering that this is an SPM repository, the Framework is more than 10MB, which will further affect the download speed through the SPM method. So I created a new repository myself (iOS only), and if you have time, you can also take a look(https://github.com/xing3523/LocalHotReloading). The implementation is not very complex, and maybe you can also create a similar repository and make it more complete (such as including macOS or others). I would be very glad to see that and use it.

**Comment by johnno1962** [comment]
Hi, As an alternative to SPM have you considered using one of the "pre-built bundles" in the app package as described in the InjectionIII README? You use the `copy_bundle.sh` script in the app bundle in a build phase to copy a bundle into your app and then the following code to load it. This would be equivalent to using SPM or your pod.
```
    #if DEBUG
    if let path = Bundle.main.path(forResource:
            "iOSInjection", ofType: "bundle") ??
        Bundle.main.path(forResource:
            "macOSInjection", ofType: "bundle") {
        Bundle(path: path)!.load()
    }
    #endif
```
I'd rather not create another binary distribution channel than the app, particularly not one using cocoapods.

**Comment by xing3523** [comment]
Is that OK? I tried to copy to the project, error signature invalid
```
Error loading /var/containers/Bundle/Application/BE919E03-11E9-4222-8807-502EBECE39ED/LocalHotReloadingDemo.app/iOSInjection.bundle/iOSInjection:  dlopen(/var/containers/Bundle/Application/BE919E03-11E9-4222-8807-502EBECE39ED/LocalHotReloadingDemo.app/iOSInjection.bundle/iOSInjection, 265): no suitable image found.  Did find:
	/var/containers/Bundle/Application/BE919E03-11E9-4222-8807-502EBECE39ED/LocalHotReloadingDemo.app/iOSInjection.bundle/iOSInjection: code signature invalid for '/var/containers/Bundle/Application/BE919E03-11E9-4222-8807-502EBECE39ED/LocalHotReloadingDemo.app/iOSInjection.bundle/iOSInjection'
```

**Comment by johnno1962** [comment]
Did you use the script? That should look after signing for you. You need to call the following as a build phase:
```
RESOURCES=/Applications/InjectionIII.app/Contents/Resources
if [ -f "$RESOURCES/copy_bundle.sh" ]; then
    "$RESOURCES/copy_bundle.sh"
fi

**Comment by xing3523** [comment]
Got it. Let me try this way later, thanks.
