### ISSUE TITLE
Neither InjectionIII approach nor HotReloading as an added package worked for Vapor app

### ISSUE THREAD

**Issue by genkernel** [johnno1962/HotReloading#98]
I tried both approaches with Injection and no package and then not running InejctionIII and included package with linker flags in Package.swift as specified on the main gh page.

In both cases I see "good" logs that tell that it recompiled and interposed OK.

🔥 Using logs: ...
🔥 Compiling <filen-path>
🔥 Loading .dylib ...
🔥 Interposed 1 function references.

However when I send a new http request it spits out old log in the console (logged via `req.logger.info`).
The way Im testing to confirm that injection is working is by changing log text.

When using InjectionIII approach its icon changed to orange OK.

Any tips?

**Comment by johnno1962** [comment]
HI, Vapor is a bit complicated as it frequently uses stored closures to implement a route. InjectionIII can only replace function dispatches, it has no way of knowing how to replace these stored closures. It should work if you have your closure delegate to a method on a class or function which should inject.

**Comment by genkernel** [comment]
> HI, Vapour is a bit complicated as it frequently uses stored closures to implement a route. InjectionIII can only replace function dispatches, it has no way of knowing how to replace these stored closures. It should work if you have your closure delegate to a method on a class or function which should inject.

That did the trick. Thanks for quick reply!
