### ISSUE TITLE
Working with XCode 16?

### ISSUE THREAD

**Issue by genkernel** [johnno1962/HotReloading#99]
Just a question. 
Hot reloading stopped working for me after updating to Xcode 16. Is it me or xcode 16 not supported?

**Comment by johnno1962** [comment]
Hi, What's not working? Which version of the app are you using? Xcode 16 has been supported since the 5.0.1 release here on GitHub. A change was required to keep "interposing" working.

**Comment by genkernel** [comment]
Resolved. Thanks for the quick reply!

I don't know what version I was using since I do not check xcode's logs related to packages.
But I've removed hot-reloading package from the prj when it stopped working (for me) and added it back today - long story short - it works.
